name: Manual release

on:
  workflow_dispatch:
    inputs:
      version_tag:
        required: true
        type: string
        default: v0.0.0
      dist_file_name:
        required: true
        type: string
        default: d-fav-coupon-filter

jobs:
  release:
    uses: ./.github/workflows/release-build.yml
    with:
      version_tag: ${{ inputs.version_tag }}
      dist_file_name: ${{ inputs.dist_file_name }}
    permissions:
      contents: write
