name: Build Userscript

on:
  workflow_dispatch:
    inputs:
      version_tag:
        required: true
        type: string
      dist_file_name:
        required: true
        type: string
        default: d-fav-coupon-filter

permissions:
  contents: write

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm ci
      - run: npm run build
      - run: gh release create ${{ inputs.version_tag }} --draft --generate-notes dist/${{ inputs.dist_file_name }}.user.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
